# Generated by Django 5.1.3 on 2024-11-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('Funcional', 'Funcional'), ('Não Funcional', 'Não Funcional')], max_length=20)),
            ],
        ),
    ]
